#include <Arduino.h>
#include <LittleFS.h>
#include <ESP8266WiFi.h>
#include <ESP8266WebServer.h>
#include <PubSubClient.h>
#include <ArduinoJson.h>
#include <SoftwareSerial.h>
#include "config.h"
SoftwareSerial panelSerial(PANEL_RX_PIN, PANEL_TX_PIN, false, 96);
ESP8266WebServer server(HTTP_PORT);
WiFiClient wifiClient; PubSubClient mqttClient(wifiClient);
struct RelayItem{ String name; bool state; }; RelayItem relays[RELAY_COUNT];
unsigned long lastWifiAttempt=0,lastMqttAttempt=0,lastPanelSync=0; const char* CONFIG_FILE="/config.json";
bool relayOnLevel(){ return RELAY_ACTIVE_LOW ? LOW : HIGH; } bool relayOffLevel(){ return RELAY_ACTIVE_LOW ? HIGH : LOW; }
void setRelayPhysical(uint8_t i,bool on){ digitalWrite(RELAY_PINS[i], on?relayOnLevel():relayOffLevel()); }
void saveConfig(){ DynamicJsonDocument doc(2048); JsonArray arr=doc.createNestedArray("relays"); for(uint8_t i=0;i<RELAY_COUNT;i++){ JsonObject item=arr.createNestedObject(); item["name"]=relays[i].name; item["state"]=relays[i].state; } File f=LittleFS.open(CONFIG_FILE,"w"); if(!f)return; serializeJsonPretty(doc,f); f.close(); }
void loadDefaults(){ for(uint8_t i=0;i<RELAY_COUNT;i++){ relays[i].name="Rele "+String(i+1); relays[i].state=false; } }
void loadConfig(){ loadDefaults(); if(!LittleFS.exists(CONFIG_FILE)){ saveConfig(); return; } File f=LittleFS.open(CONFIG_FILE,"r"); if(!f) return; DynamicJsonDocument doc(2048); if(deserializeJson(doc,f)){ f.close(); return; } f.close(); JsonArray arr=doc["relays"].as<JsonArray>(); uint8_t i=0; for(JsonVariant v:arr){ if(i>=RELAY_COUNT)break; relays[i].name=String((const char*)v["name"] | ("Rele "+String(i+1)).c_str()); relays[i].state=v["state"]|false; i++; } }
void applyRelayStates(){ for(uint8_t i=0;i<RELAY_COUNT;i++){ pinMode(RELAY_PINS[i],OUTPUT); setRelayPhysical(i,relays[i].state);} }
String jsonStatus(){ DynamicJsonDocument doc(2048); doc["ip"]=WiFi.localIP().toString(); doc["wifi_connected"]=WiFi.isConnected(); doc["mqtt_connected"]=mqttClient.connected(); doc["mqtt_base_topic"]=MQTT_BASE_TOPIC; JsonArray arr=doc.createNestedArray("relays"); for(uint8_t i=0;i<RELAY_COUNT;i++){ JsonObject item=arr.createNestedObject(); item["index"]=i+1; item["name"]=relays[i].name; item["state"]=relays[i].state; } String out; serializeJson(doc,out); return out; }
void panelSendLine(const String &line){ panelSerial.println(line); }
void pushAllToPanel(){ for(uint8_t i=0;i<RELAY_COUNT;i++){ panelSendLine("NAME:"+String(i+1)+":"+relays[i].name); panelSendLine("STATE:"+String(i+1)+":"+String(relays[i].state?"1":"0")); } panelSendLine("SYNC:DONE"); }
void publishRelayState(uint8_t i){ if(!mqttClient.connected()) return; String t=String(MQTT_BASE_TOPIC)+"/relay/"+String(i+1)+"/state"; mqttClient.publish(t.c_str(), relays[i].state?"ON":"OFF", true); String nt=String(MQTT_BASE_TOPIC)+"/relay/"+String(i+1)+"/name"; mqttClient.publish(nt.c_str(), relays[i].name.c_str(), true); }
void publishAvailability(){ if(!mqttClient.connected()) return; String t=String(MQTT_BASE_TOPIC)+"/status"; mqttClient.publish(t.c_str(),"online",true); }
void setRelayState(uint8_t i,bool on,bool save=true,bool announce=true){ if(i>=RELAY_COUNT)return; relays[i].state=on; setRelayPhysical(i,on); if(save) saveConfig(); if(announce){ publishRelayState(i); pushAllToPanel(); } }
void toggleRelay(uint8_t i){ if(i<RELAY_COUNT) setRelayState(i,!relays[i].state); }
String htmlEscape(const String &s){ String out; for(size_t i=0;i<s.length();i++){ char c=s[i]; if(c=='&') out+="&amp;"; else if(c=='<') out+="&lt;"; else if(c=='>') out+="&gt;"; else if(c=='\"') out+="&quot;"; else out+=c; } return out; }
String htmlPage(){ String html=R"rawliteral(<!doctype html><html lang='no'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'><title>Relépanel</title><style>:root{--bg:#0f172a;--card:#111827;--line:#334155;--txt:#e5eefc;--muted:#94a3b8}*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;background:linear-gradient(135deg,#020617,#0f172a 55%,#1e293b);color:var(--txt)}.wrap{max-width:1100px;margin:0 auto;padding:24px}.grid,.topbar{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}.card{background:rgba(17,24,39,.92);border:1px solid var(--line);border-radius:18px;padding:18px}.row{display:flex;justify-content:space-between;align-items:center;gap:12px}.badge{padding:6px 12px;border-radius:999px;font-weight:700;font-size:12px;text-transform:uppercase}.on{background:rgba(34,197,94,.18);color:#86efac}.off{background:rgba(239,68,68,.18);color:#fca5a5}button{border:0;border-radius:12px;padding:10px 14px;font-weight:700;cursor:pointer}.btn-on{background:#22c55e}.btn-off{background:#ef4444}.btn-save{background:#38bdf8}input[type=text]{width:100%;background:#020617;border:1px solid var(--line);color:var(--txt);border-radius:12px;padding:10px 12px;margin:12px 0}.small{color:var(--muted);font-size:13px}</style></head><body><div class='wrap'><h1>⚡ Relépanel</h1><div class='topbar'><div class='card'><div class='small'>IP-adresse</div><div id='ip'>%IP%</div></div><div class='card'><div class='small'>WiFi</div><div id='wifi'>%WIFI%</div></div><div class='card'><div class='small'>MQTT</div><div id='mqtt'>%MQTT%</div></div><div class='card'><div class='small'>Base topic</div><div>%TOPIC%</div></div></div><div class='grid'>)rawliteral";
 for(uint8_t i=0;i<RELAY_COUNT;i++){ html+="<div class='card'><div class='row'><div><div class='small'>Kanal "+String(i+1)+"</div><h2 style='margin:4px 0 0'>"+htmlEscape(relays[i].name)+"</h2></div><div class='badge "+String(relays[i].state?"on":"off")+"'>"+String(relays[i].state?"PÅ":"AV")+"</div></div><div class='row' style='margin-top:10px'><button class='btn-on' onclick='setRelay("+String(i+1)+",1)'>⏻ PÅ</button><button class='btn-off' onclick='setRelay("+String(i+1)+",0)'>⭘ AV</button></div><input id='name"+String(i+1)+"' type='text' value='"+htmlEscape(relays[i].name)+"' maxlength='24'><button class='btn-save' onclick='saveName("+String(i+1)+")'>💾 Lagre navn</button></div>"; }
 html += R"rawliteral(</div><div style='margin-top:22px;color:#94a3b8;font-size:13px'>Styring via web, UNO-frontpanel og MQTT. Status oppdateres hvert 2. sekund.</div></div><script>async function setRelay(index,state){await fetch(`/api/relay/${index}/set?state=`+state,{method:'POST'});refreshStatus();}async function saveName(index){const name=document.getElementById(`name${index}`).value;await fetch(`/api/relay/${index}/name`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'name='+encodeURIComponent(name)});refreshStatus();}async function refreshStatus(){const res=await fetch('/api/status');const data=await res.json();document.getElementById('ip').textContent=data.ip;document.getElementById('wifi').textContent=data.wifi_connected?'Tilkoblet':'Frakoblet';document.getElementById('mqtt').textContent=data.mqtt_connected?'Tilkoblet':'Frakoblet';if(data.relays){data.relays.forEach((r,idx)=>{const input=document.getElementById(`name${idx+1}`);if(document.activeElement!==input) input.value=r.name;});}setTimeout(refreshStatus,2000);}refreshStatus();</script></body></html>)rawliteral";
 html.replace("%IP%",WiFi.localIP().toString()); html.replace("%WIFI%",WiFi.isConnected()?"Tilkoblet":"Frakoblet"); html.replace("%MQTT%",mqttClient.connected()?"Tilkoblet":"Frakoblet"); html.replace("%TOPIC%",String(MQTT_BASE_TOPIC)); return html; }
void handleRoot(){ server.send(200,"text/html; charset=utf-8",htmlPage()); } void handleStatus(){ server.send(200,"application/json",jsonStatus()); }
void handleRelaySet(){ String uri=server.uri(); int p2=uri.lastIndexOf('/'); String idStr=uri.substring(11,p2); int idx=idStr.toInt()-1; String stateArg=server.arg("state"); bool on=(stateArg=="1"||stateArg=="on"||stateArg=="ON"||stateArg=="true"); setRelayState(idx,on); server.send(200,"application/json",jsonStatus()); }
void handleRelayName(){ String uri=server.uri(); int p2=uri.lastIndexOf('/'); String idStr=uri.substring(11,p2); int idx=idStr.toInt()-1; if(idx<0||idx>=RELAY_COUNT){ server.send(400,"text/plain","Bad relay index"); return; } String name=server.arg("name"); name.trim(); if(!name.length()) name="Rele "+String(idx+1); if(name.length()>24) name=name.substring(0,24); relays[idx].name=name; saveConfig(); publishRelayState(idx); pushAllToPanel(); server.send(200,"application/json",jsonStatus()); }
void setupWeb(){ server.on("/",HTTP_GET,handleRoot); server.on("/api/status",HTTP_GET,handleStatus); for(uint8_t i=1;i<=RELAY_COUNT;i++){ server.on(("/api/relay/"+String(i)+"/set").c_str(),HTTP_POST,handleRelaySet); server.on(("/api/relay/"+String(i)+"/name").c_str(),HTTP_POST,handleRelayName);} server.begin(); }
void mqttCallback(char* topic, byte* payload, unsigned int length){ String t=topic; String message; for(unsigned int i=0;i<length;i++) message+=(char)payload[i]; message.trim(); for(uint8_t i=0;i<RELAY_COUNT;i++){ String st=String(MQTT_BASE_TOPIC)+"/relay/"+String(i+1)+"/set"; String nt=String(MQTT_BASE_TOPIC)+"/relay/"+String(i+1)+"/name/set"; if(t==st){ bool on=(message=="ON"||message=="1"||message=="true"); setRelayState(i,on); return; } if(t==nt){ relays[i].name=message.length()?message.substring(0,24):("Rele "+String(i+1)); saveConfig(); publishRelayState(i); pushAllToPanel(); return; } } }
void mqttConnect(){ if(mqttClient.connected()) return; if(millis()-lastMqttAttempt<5000) return; lastMqttAttempt=millis(); String willTopic=String(MQTT_BASE_TOPIC)+"/status"; bool ok; if(String(MQTT_USER).length()) ok=mqttClient.connect(MQTT_CLIENT_ID,MQTT_USER,MQTT_PASSWORD,willTopic.c_str(),0,true,"offline"); else ok=mqttClient.connect(MQTT_CLIENT_ID,willTopic.c_str(),0,true,"offline"); if(!ok) return; publishAvailability(); for(uint8_t i=0;i<RELAY_COUNT;i++){ mqttClient.subscribe((String(MQTT_BASE_TOPIC)+"/relay/"+String(i+1)+"/set").c_str()); mqttClient.subscribe((String(MQTT_BASE_TOPIC)+"/relay/"+String(i+1)+"/name/set").c_str()); publishRelayState(i);} }
void wifiConnect(){ if(WiFi.isConnected()) return; if(millis()-lastWifiAttempt<8000) return; lastWifiAttempt=millis(); WiFi.mode(WIFI_STA); WiFi.begin(WIFI_SSID,WIFI_PASSWORD); }
void handlePanelCommand(const String &cmd){ if(cmd=="GET:ALL"){ pushAllToPanel(); return; } if(cmd.startsWith("TOGGLE:")){ int idx=cmd.substring(7).toInt()-1; if(idx>=0&&idx<RELAY_COUNT) toggleRelay(idx); return; } if(cmd.startsWith("SET:")){ int sep=cmd.indexOf(':',4); if(sep>0){ int idx=cmd.substring(4,sep).toInt()-1; int val=cmd.substring(sep+1).toInt(); if(idx>=0&&idx<RELAY_COUNT) setRelayState(idx,val==1); } } }
void readPanelSerial(){ static String line; while(panelSerial.available()){ char c=(char)panelSerial.read(); if(c=='\r') continue; if(c=='\n'){ if(line.length()){ handlePanelCommand(line); line=""; } } else { line+=c; if(line.length()>120) line.remove(0,40); } } }
void setup(){ for(uint8_t i=0;i<RELAY_COUNT;i++) pinMode(RELAY_PINS[i],OUTPUT); Serial.begin(115200); panelSerial.begin(PANEL_BAUD); LittleFS.begin(); loadConfig(); applyRelayStates(); wifiConnect(); mqttClient.setServer(MQTT_HOST, MQTT_PORT); mqttClient.setCallback(mqttCallback); setupWeb(); pushAllToPanel(); }
void loop(){ wifiConnect(); if(WiFi.isConnected()) mqttConnect(); mqttClient.loop(); server.handleClient(); readPanelSerial(); if(millis()-lastPanelSync>10000){ lastPanelSync=millis(); pushAllToPanel(); } }
